### ISSUE TITLE
Send attach jpg to chat?

### ISSUE THREAD

**Issue by Classsic** [a-sync/slackr#2]
I want to know if is possible send a jpg image or video to channel with this tool. 
Text work awesome.
If you can add send attach, I will create a docker.
Thanks.
Classsic.

**Comment by a-sync** [comment]
Hi there,
the scope of this script is the incoming **webhook URL** API which doesn't allow file uploads.

You can use a different slack API, and a **token** (different from webhook url) to upload files, i recommend you check out it's API docu page: https://api.slack.com/methods/files.upload
```bash
curl -F file=@dramacat.gif -F channels=C024BE91L,#general -F token=xxxx-xxxxxxxxx-xxxx https://slack.com/api/files.upload
```
This also returns a share url and a download url as a response which you can pipe via slackr.
I also recommend you check out [slacktee.sh](https://github.com/course-hero/slacktee) which implements this API aswell

Kind regards,
  a-sync

**Comment by a-sync** [comment]
@Classsic i created a different script, [slackfu](https://github.com/a-sync/slackfu) (slack file upload) to deal with file uploads / snippets. 
It uses the slack web API, which means you will need a slack authentication token.

https://github.com/a-sync/slackfu

Give it a try. 
Kind regards,
  a-sync
